language: python
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
env:
  global:
    - TWINE_USERNAME=charlie137 
script:
  - $PIP install cibuildwheel==0.6.0
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PIP install twine
      python -m twine upload wheelhouse/*.whl
    fi
